theme: minima
title: Code To Learn Blog
author: David Saah
email: dasorange.hope@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official blog of Code To Learn community.

# social links
twitter_username: dave_saah # DO NOT include the @ character, or else the build will fail!
github_username:  DaveSaah # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
